### PR TITLE
Add command management endpoints

### LINKED ISSUE #69: Create new endpoint on the Command Manager plugin
## Description

We need to create a new HTTP Rest API to the Command Manager plugin, exposing a POST endpoint that receives the command action request from the Management API on the Wazuh Server node, or from the Content Manager plugin (this is yet to be defined). Independently of the source, the Command Manager endpoint must receive this information, fit it into the Command index data model and persist the data on the index.

The endpoint must define the endpoint and its parameters, validate the data and persist it as the Commands index data model requires.

Be aware of any security concerns. On a next iteration, we want to secure the endpoint, so only allowed clients are allowed to use the endpoint.

## Tasks

- [x] Implement the ActionPlugin interface
- [x] Implement the Rest endpoint (resthandler, model, ...)
- [ ] Validate the data
- [x] Persist the data into the commands index.

### PR DESCRIPTION
**Pull request by f-galland**
### Description
This PR adds HTTP endpoints to the Command Manager plugin that will be used to queue/schedule tasks.

### Issues Resolved
Resolves #69

### CODE REVIEW

**Comment by f-galland** [comment]
I added validation inspired by the `opensearch-job-scheduler` plugin repository model.

I'm currently getting an error when indexing:

```shellsession
$ curl -XPOST "http://127.0.0.1:9200/_plugins/_commandmanager/1234" -H 'Content-Type: application/json' -d'
{
  "command_order_id": "value",
  "command_request_id": "value",
  "command_source": "value",
  "command_target": "value",
  "command_timeout": "value",
  "command_type": "value",
  "command_user": "value",
  "command_action": {"field":"value"},
  "command_result": {"field":"value"}
}'


{"response":"failed"}
```

The engine logs are showing the following error:
```
java.lang.NullPointerException: Cannot read field "commandOrderId" because "copyCommandDetails" is null
	at com.wazuh.commandmanager.model.CommandDetails.<init>(CommandDetails.java:159) ~[?:?]
```

**Comment by f-galland** [comment]
I removed the document update functionality off the plugin after discussion with Alex, with [this change](https://github.com/wazuh/wazuh-indexer-plugins/pull/72/commits/475514195f284e352eb305892f29e8c88ccfd900), the endpoint now works as expected:

```shellsession



$ curl -XPOST "http://127.0.0.1:9200/command-manager/_search?pretty" -H 'Content-Type: application/json' -d'
{
   "size": 1,
   "query": {
      "match_all": {}
   }
}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "command-manager",
        "_id" : "JEChD5IBPt7qjCU0RVfs",
        "_score" : 1.0,
        "_source" : {
          "command_order_id" : "value",
          "command_request_id" : "value",
          "command_source" : "value",
          "command_target" : "value",
          "command_timeout" : "value",
          "command_type" : "value",
          "command_user" : "value",
          "command_action" : {
            "field" : "value"
          },
          "command_result" : {
            "field" : "value"
          }
        }
      }
    ]
  }
}
```

**Comment by f-galland** [comment]
The order and request IDs are generated randomly (for tests purposes) and the document ID is a concatenation of both:

```shellsession
$ 
curl -XPOST "http://127.0.0.1:9200/_plugins/_commandmanager" -H 'Content-Type: application/json' -d'
{
  "command_order_id": "value",
  "command_request_id": "value",
  "command_source": "value",
  "command_target": "value",
  "command_timeout": "value",
  "command_type": "value",
  "command_user": "value",
  "command_action": {"field":"value"},
  "command_result": {"field":"value"}
}'
{"response":"success","document_id":"pBjePGfvgm"}



fede@tyner:~
$ curl -XPOST "http://127.0.0.1:9200/command-manager/_search?pretty" -H 'Content-Type: application/json' -d'
{
   "size": 1,
   "query": {
      "match_all": {}
   }
}'




{
  "took" : 40,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "command-manager",
        "_id" : "pBjePGfvgm",
        "_score" : 1.0,
        "_source" : {
          "command_order_id" : "pBjeP",
          "command_request_id" : "Gfvgm",
          "command_source" : "value",
          "command_target" : "value",
          "command_timeout" : "value",
          "command_type" : "value",
          "command_user" : "value",
          "command_action" : {
            "field" : "value"
          },
          "command_result" : {
            "field" : "value"
          }
        }
      }
    ]
  }
}

```

**Review by AlexRuiz7 — APPROVED** [review]
LGTM

**Pull request merged**
